name: num_to_word_krd
description: A Dart package to convert number to kurdish words.
version: 1.0.1
repository: https://github.com/awderz4/num_to_word_krd

environment:
  sdk: ^3.0.6


dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
